CREATE DATABASE IF NOT EXISTS resume;
USE resume;

CREATE TABLE IF NOT EXISTS data (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  FullName VARCHAR(100),
  Email VARCHAR(100),
  PhoneNumber BIGINT(15),
  Address VARCHAR(100),
  EducationBackground VARCHAR(500),
  WorkExperience VARCHAR(500),
  Skills VARCHAR(500),
  CreatedData TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
